apiVersion: v1
kind: Secret
metadata:
  name: execution-service-secrets
type: Opaque
stringData:
  DB_HOST: "${DB_HOST}"
  DB_PORT: "${DB_PORT}"
  DB_USERNAME: "${DB_USERNAME}"
  DB_PASSWORD: "${DB_PASSWORD}"
  DB_DATABASE: "${DB_DATABASE}"
  MONGO_HOST: "${MONGO_HOST}"
  MONGO_DB: "${MONGO_DB}"
  JWT_SECRET: "${JWT_SECRET}"
  AWS_REGION: "${AWS_REGION}"
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  SQS_OS_EVENTS_QUEUE_URL: "${SQS_OS_EVENTS_QUEUE_URL}"
  SQS_BILLING_EVENTS_QUEUE_URL: "${SQS_BILLING_EVENTS_QUEUE_URL}"
  SQS_EXECUTION_EVENTS_QUEUE_URL: "${SQS_EXECUTION_EVENTS_QUEUE_URL}"